env:
  browser: true
  es2021: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - 'plugin:jest/recommended'
  - 'plugin:jsx-a11y/recommended'
  - 'plugin:import/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - jest
  - jsx-a11y
  - import
rules:
  import/extensions: off
  no-console: off
  react/prop-types: off
  react/function-component-definition: [2, { "namedComponents": "arrow-function" }]
