env:
  es2021: true
  node: true
  jest: true

extends:
  - airbnb-base
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: 12
  sourceType: module

plugins:
  - jest

rules:
  no-console: off
  import/extensions: off
  class-methods-use-this: off
  no-underscore-dangle: [1, { allow: ['__dirname'] }]

overrides:
  - files: '*.test.js'
    rules:
      no-param-reassign: off
      camelcase: off
