version: "3.8"
services:
  ical:
    build: .
    volumes:
      - .:/usr/src/app
    image: melodyn:ical
    container_name: melodyn_ical
  postgres:
    image: library/postgres:12
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ical
    ports:
    - 5432:5432
