env:
  es2021: true
  node: true
  jest: true

extends:
  - airbnb-base
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: 12
  sourceType: module

plugins:
  - jest

rules:
  camelcase: off
  no-console: off
  import/extensions: off
  class-methods-use-this: off
  no-underscore-dangle: [1, { allow: ['__dirname'] }]
  max-classes-per-file: off
  max-len: ["error", {
    "code": 120,
    "ignoreComments": true,
    "ignoreTrailingComments": true,
    "ignoreUrls": true,
    "ignoreStrings": true,
    "ignoreTemplateLiterals": true
  }]

overrides:
  - files: '*.test.js'
    rules:
      no-param-reassign: off
  - files: 'libs/cron/CronService.js'
    rules:
      no-await-in-loop: off
