version: "3.8"
services:
  ical:
    build: .
    volumes:
      - .:/usr/src/app
    image: app:ical
    container_name: app_ical
    ports:
      - 8080:8080
  postgres-dev:
    image: library/postgres:12
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ical
    ports:
      - 5432:5432
  postgres-test:
    image: library/postgres:12
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ical_test
    ports:
      - 5433:5432
