name: Frontend
on:
  push:
    branches: frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - name: Build
      - run: make ci-build
      - name: Commit report
        run: |
          git config --global user.name 'Sergei Melodyn'
          git config --global user.email 'samelodyn@gmail.com'
          git add ./public/*
          git commit -am "Release"
          git push -u origin gh-pages --tags
