name: Frontend CI
on:
  push:
    branches: frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build and deploy
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - run: make ci-build
      - run: |
          cp -r ./public/* ./
      - run: |
          git config --global user.name 'Sergei Melodyn'
          git config --global user.email 'samelodyn@gmail.com'
          git add .
          git commit -am "Release"
      - run: git status
      - run: git push -u origin gh-pages --force
