name: Frontend CI
on:
  push:
    branches: frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build and deploy
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - run: make ci-build
      - run: |
          rm -rf node_modules
          mkdir app
          mv ./* ./.* ./app
          cp -r ./app/public/* ./
          rm -rf ./app
      - run: |
          git init
          git config --global user.name 'Sergei Melodyn'
          git config --global user.email 'samelodyn@gmail.com'
          git add .
          git commit am "Release"
          git push -u origin gh-pages
